### PR TITLE
Fix mobile navbar closes #34

### LINKED ISSUE #34: Make the buttons work on the phone
For some reason, we cannot get to the Product, Research, etc. from the phone. I wonder if this would be a hard fix.

### PR DESCRIPTION
**Pull request by jayden626**
Imported Bootstrap into the `NavbarDefault.vue`. Not sure why this is required, since it isn't found anywhere in the [theme this website is based on](https://github.com/creativetimofficial/vue-material-kit), but it fixes the issue

Closes #34

### CODE REVIEW

File: src/examples/navbars/NavbarDefault.vue [hunk 1]
```diff
@@ -184,8 +184,8 @@ watch(
               />
             </a>
             <div
-              class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
-              aria-labelledby="dropdownMenuPages"
+              class="dropdown-menu ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3"
```
Comment (jayden626) [inline src/examples/navbars/NavbarDefault.vue:187]: `dropdown-menu-animation` caused weird spacing issues on the mobile menu. The spacing was more off-putting than the lack of animation, so I just removed it.

example without it removed:
image


example with it removed:
image
